### ISSUE TITLE
The project cannot be started directly

### ISSUE THREAD

**Issue by piotrek-k** [adiospl/WykopSharp#1]
Hej,
przy próbie uruchomienia aplikacji pokazuje mi się taki komunikat:
http://imgur.com/693rbKK
Nie wiesz o co może chodzić?

**Comment by adiospl** [comment]
@MyPCIsBetter Target Typem aplikacji jest biblioteka, więc nie można od tak uruchomić biblioteki :). Musisz stworzyć swoją aplikację i dodać projekty do solucji i dodaj referencje do projektów. 
![konfiguracja](http://i.imgur.com/X0SrA45.png)
